[agent]
name = "privesc_agent"
description = "Expert in privilege escalation for Linux and Windows systems"
system_prompt = ["common.md", "session.md", "privesc_agent.md"]

tools = [
    "shell",
    "wait",
]
handoffs = ["triage_agent", "recon_agent", "exploit_agent", "web_exploit_agent"]

[agent.llm]
temperature = 0.4